<a href="https://colab.research.google.com/github/drsubirghosh2008/drsubirghosh2008/blob/main/Copy_of_PW_Assignment__18_23_10_24_Statistics_Basic_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. What are the three measures of central tendency?

Answer:
The three measures of central tendency are:

Mean: The arithmetic average of a set of values, calculated by summing all the numbers and dividing by the total number of values.

Median: The middle value when the data set is ordered from smallest to largest. If there is an even number of observations, the median is the average of the two middle numbers.

Mode: The value that appears most frequently in a data set. A data set can have more than one mode if multiple values appear with the same frequency.

Q2. What is the difference between the mean, median, and mode? How are they used to measure the central tendency of a dataset?

Answer:

The mean, median, and mode are all measures of central tendency, but they capture different aspects of how data points are distributed in a dataset. Here's the difference between them:

1. Mean (Average):
Definition: The mean is the sum of all the values divided by the number of values.

Use: It gives a general idea of the data's central value and is widely used in various applications.

Sensitivity: The mean is sensitive to extreme values (outliers). A few very high or low values can skew the mean significantly.

Example: If the data set is [1, 2, 3, 4, 100], the mean is (1+2+3+4+100) / 5 = 22, which is not representative of most of the values.

2. Median:
Definition: The median is the middle value in an ordered data set. If the dataset has an odd number of observations, it is the middle number; if even, it’s the average of the two middle numbers.
Use: The median is a better measure of central tendency when the data contains outliers or is skewed, as it isn't influenced by extreme values.
Sensitivity: It is resistant to outliers.
Example: For the data set [1, 2, 3, 4, 100], the median is 3, which better reflects the center of the bulk of the data.
3. Mode:
Definition: The mode is the value that appears most frequently in the data set. A dataset can have more than one mode (bimodal, multimodal).

Use: The mode is useful for categorical data or when the most common value needs to be identified. It doesn't consider all values but focuses on frequency.
Sensitivity: It doesn’t consider the magnitude of other values; it just focuses on frequency.

Example: In a dataset like [1, 1, 2, 2, 2, 3, 4], the mode is 2 because it appears most frequently.

When to Use Each Measure:

Mean: Use when data is symmetric and free of extreme outliers. It gives an overall central value.
Median: Use when data is skewed or contains outliers. The median provides a better center for the majority of the data.
Mode: Use for finding the most frequent value, especially in categorical data, or in cases where you're interested in the most typical or common value.

Q3. Measure the three measures of central tendency for the given height data:
[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]

Answer

For the given height data:

Mean: 177.02 (approximately)
Median: 177.0
Mode: 177.0
These values indicate that most of the heights cluster around 177 cm.

In [ ]:
import numpy as np
from scipy import stats

# Given height data
height_data = [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]

# Calculating mean, median, and mode
mean_height = np.mean(height_data)
median_height = np.median(height_data)
mode_height = stats.mode(height_data)

# mean_height, median_height, mode_height.mode[0]
print(mean_height, median_height, mode_height)

177.01875 177.0 ModeResult(mode=177.0, count=3)


Q4. Find the standard deviation for the given data:
[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]

Answer:

The standard deviation for the given height data is approximately 1.79. This indicates that the heights vary by about 1.79 cm from the mean on average.

In [ ]:
# Calculating the standard deviation for the given height data
std_deviation = np.std(height_data)

std_deviation


1.7885814036548633

Q5. How are measures of dispersion such as range, variance, and standard deviation used to describe the spread of a dataset? Provide an example.

Answer:


Measures of dispersion, such as range, variance, and standard deviation, describe how spread out the data points are in a dataset. They give insight into the variability or consistency of the data.

1. Range:

Definition: The range is the difference between the maximum and minimum values in the dataset.

Use: It gives a quick sense of how spread out the extreme values are, but it only considers the two extreme points, ignoring the distribution of the other data.

Example: In a dataset of heights [175, 176, 177, 178, 179, 180], the range would be 180 - 175 = 5 cm.

2. Variance:

Definition: Variance measures the average squared deviation of each number from the mean. It reflects the overall spread of the data.
Use: It gives an idea of how far data points are from the mean on average, but because it involves squaring the differences, it’s harder to interpret in the original units of measurement.

Example: If the mean height is 177 cm, and individual heights are close to 177, the variance will be small. A larger variance would suggest more variability in the heights.

3. Standard Deviation:

Definition: Standard deviation is the square root of the variance. It brings the units back to the same scale as the original data, making it easier to interpret.

Use: It gives an indication of how much, on average, the data points deviate from the mean. It’s commonly used because it’s in the same units as the data.

Example: If the standard deviation of the heights is 1.79 cm (as in the earlier example), most heights will be within ±1.79 cm of the mean (177.02 cm), meaning that the data is relatively concentrated around the mean.

Example Dataset:

Consider two sets of exam scores for students:

Class A: [80, 85, 90, 95, 100]

Class B: [60, 70, 80, 90, 100]

Range:

Class A: 100 - 80 = 20
Class B: 100 - 60 = 40
The range of Class B is larger, indicating more spread.

Variance:

Class A has a smaller variance than Class B, meaning that Class A's scores are more tightly clustered around the mean, while Class B has more variability.

Standard Deviation:

Class A's standard deviation will be smaller than Class B’s, indicating that the scores in Class A are more consistent.

Summary:

Range: Provides a simple measure of spread but is affected by extreme values (outliers).
Variance: Quantifies how much the data points differ from the mean on average, but in squared units.
Standard Deviation: Gives an easy-to-interpret measure of spread in the same units as the data, widely used for understanding variability.

Q6. What is a Venn diagram?

Answer:


A Venn diagram is a visual tool used to represent the relationships between different sets or groups of objects. It consists of overlapping circles, where each circle represents a set, and the overlaps show the common elements between the sets.

Key Components:

Circles: Each circle represents a set of items, numbers, or elements.
Overlapping areas: The areas where circles overlap show elements that are common to the sets.

Non-overlapping areas: These represent elements that are unique to a specific set.

Uses of Venn Diagrams:

Set Theory: To illustrate the relationships between sets, such as unions, intersections, and differences.

Logic: To visualize logical relationships and solve problems involving "AND" and "OR" conditions.

Comparisons: To show similarities and differences between two or more groups, categories, or concepts.

Example:

Consider two sets:

Set A: {1, 2, 3, 4}
Set B: {3, 4, 5, 6}

A Venn diagram would show two overlapping circles. The overlap would contain {3, 4}, representing the elements common to both Set A and Set B. The non-overlapping parts would show {1, 2} for Set A and {5, 6} for Set B.

Venn diagrams are often used in math, logic, statistics, and everyday problem-solving to visualize relationships between groups.

Q7. For the two given sets A = (2,3,4,5,6,7) & B = (0,2,6,8,10). Find:
(i) A intersection B
(ii) A ⋃ B

Answer:


For the two sets:

A = {2, 3, 4, 5, 6, 7}
B = {0, 2, 6, 8, 10}
(i) A ∩ B (Intersection of A and B):
The intersection consists of elements that are common to both sets A and B.

A ∩ B = {2, 6}

(ii) A ⋃ B (Union of A and B):
The union consists of all elements from both sets, without duplication.

A ⋃ B = {0, 2, 3, 4, 5, 6, 7, 8, 10}

So:

A ∩ B = {2, 6} and
A ⋃ B = {0, 2, 3, 4, 5, 6, 7, 8, 10}

Q8. What do you understand about skewness in data?

Answer:

Skewness refers to the asymmetry in the distribution of data values around its mean. In a perfectly symmetrical distribution, the left and right sides are mirror images of each other, and the skewness is zero. However, when data is not symmetrically distributed, the distribution may be skewed, meaning it has a longer tail on one side than the other.

Types of Skewness:

Positive Skewness (Right-Skewed):

Description: In a positively skewed distribution, the tail on the right side (higher values) is longer than on the left. This means that the majority of the data points are clustered on the left (lower values), and there are a few extreme values (outliers) on the right.

Effect on Central Tendency: The mean is greater than the median, and the mode is typically less than the median.

Example: Income distribution is often positively skewed because most people earn in the lower to middle ranges, but a few individuals earn very high incomes.

Negative Skewness (Left-Skewed):

Description: In a negatively skewed distribution, the tail on the left side (lower values) is longer. The majority of the data points are concentrated on the right (higher values), with a few extreme low values.
Effect on Central Tendency: The mean is less than the median, and the mode is typically greater than the median.

Example: The distribution of ages at retirement may be negatively skewed, as most people retire at older ages, but a few individuals may retire very early.

No Skewness (Symmetrical or Zero Skewness):

Description: In a perfectly symmetrical distribution, the left and right sides are mirror images, and the mean, median, and mode are all equal.
Example: A normal distribution (bell curve) has no skewness.

Importance of Skewness:

Influence on Statistical Measures: Skewness can affect measures like the mean, median, and standard deviation. In skewed distributions, the mean can be misleading as a measure of central tendency because it is affected by extreme values.

Data Interpretation: Understanding skewness helps in interpreting the distribution of data, identifying outliers, and choosing appropriate statistical methods.

For example, in highly skewed data, the median might be a better measure of central tendency than the mean.

Q9. If a data is right skewed then what will be the position of median with respect to mean?

Answer:

If a data set is right-skewed (positively skewed), the distribution has a longer tail on the right (towards the higher values). In such cases:

The mean is pulled to the right by the higher values (outliers) in the tail.
The median is less affected by extreme values and remains closer to the bulk of the data.

As a result, the median will be less than the mean in a right-skewed distribution.

In summary:

For a right-skewed distribution:

Mean > Median


Q10. Explain the difference between covariance and correlation. How are these measures used in statistical analysis?

Answer:

Covariance and correlation are both measures of the relationship between two variables, but they differ in how they quantify that relationship and in their interpretation. Here’s a breakdown of the differences:

1. Covariance:

Definition: Covariance measures the direction of the linear relationship between two variables. It indicates whether the variables increase or decrease together.

Positive covariance: If the covariance is positive, the variables tend to increase together.

Negative covariance: If it is negative, when one variable increases, the other tends to decrease.

Units: The value of covariance is expressed in terms of the units of the two variables being compared, making it difficult to interpret directly or compare across datasets with different scales.

Limitations: Covariance does not give the strength of the relationship between the variables, and its magnitude depends on the scale of the variables.

2. Correlation:

Definition: Correlation measures both the strength and direction of the linear relationship between two variables. It standardizes the covariance by dividing it by the product of the standard deviations of the variables.


Correlation of +1: Perfect positive linear relationship.
Correlation of -1: Perfect negative linear relationship.
Correlation of 0: No linear relationship.


Differences in Usage:

Covariance:

Primarily used to determine the direction of the relationship between two variables (i.e., whether they tend to increase or decrease together).
Covariance is difficult to interpret when comparing variables with different units or scales, as it doesn’t normalize the values.
Covariance is often used in portfolio theory and risk management to understand how assets move together.

Correlation:

Used to measure both the strength and direction of the linear relationship between two variables.

Because it is standardized and dimensionless, it’s easier to interpret and compare across different datasets.

Correlation is widely used in statistical analysis to identify the degree of association between variables in fields like economics, biology, and social sciences.

Example:

Consider two variables: temperature (in °C) and ice cream sales (in dollars). If temperature increases, ice cream sales might also increase.

Covariance would tell you that as temperature increases, ice cream sales tend to increase (positive covariance), but the magnitude would depend on the units of the variables (degrees Celsius and dollars).

Correlation would provide a value between -1 and 1 that quantifies how strong this relationship is, independent of the units. For example, a correlation of +0.8 would indicate a strong positive linear relationship.

To conclude,
Covariance tells you if two variables move together (positive or negative relationship) but is difficult to interpret due to its dependence on the scale of the variables.

Correlation standardizes this relationship, giving a clearer picture of the strength and direction of the relationship, with values between -1 and +1, making it more interpretable and comparable across datasets.

Q11. What is the formula for calculating the sample mean? Provide an example calculation for a dataset.

Answer:


The formula for calculating the sample mean (often denoted as
𝑥
ˉ
x
ˉ
 ) is:

𝑥
ˉ
=
∑
𝑖
=
1
𝑛
𝑥
𝑖
𝑛
x
ˉ
 =
n
∑
i=1
n
​
 x
i
​

​

Where:

𝑥
ˉ
x
ˉ
  = sample mean
𝑥
𝑖
x
i
​
  = each individual observation in the sample
𝑛
n = number of observations in the sample
∑
∑ = summation symbol, which means to add up all the values

Q12. For a normal distribution data what is the relationship between its measure of central tendency?

Answer:

In a normal distribution, the measures of central tendency (mean, median, and mode) have a specific relationship due to the symmetric nature of the distribution. Here’s how they relate to each other:


Relationship in a Normal Distribution:

Mean = Median = Mode: In a perfectly normal distribution, all three measures of central tendency are equal and located at the same point on the distribution curve.

Visualization:
If you were to graph a normal distribution (bell-shaped curve):

The peak (highest point) of the curve would represent the mean, median, and mode.
The distribution is symmetric around this central point, meaning that the data values are evenly distributed on both sides.

In summary, in a normal distribution, the mean, median, and mode are all equal, indicating a perfectly balanced and symmetrical distribution of data around the central value.

Q13. How is covariance different from correlation?

Answer:

Covariance and correlation are both statistical measures that describe the relationship between two variables, but they differ in several key aspects. Here’s a detailed comparison:

Covariance:

Measures the degree to which two variables change together. It indicates whether an increase in one variable tends to be associated with an increase or decrease in another variable.

Correlation:

Measures both the strength and direction of the linear relationship between two variables. It standardizes the covariance by dividing it by the product of the standard deviations of the variables.

Covariance:
Measures the degree to which two variables change together. It indicates whether an increase in one variable tends to be associated with an increase or decrease in another variable.

Correlation:
Measures both the strength and direction of the linear relationship between two variables. It standardizes the covariance by dividing it by the product of the standard deviations of the variables.


Q14. How do outliers affect measures of central tendency and dispersion? Provide an example.

Answer:


Outliers are data points that significantly differ from the other observations in a dataset. They can have a considerable impact on measures of central tendency (mean, median, and mode) and measures of dispersion (range, variance, and standard deviation). Here's how outliers affect these measures:

Effects on Measures of Central Tendency:
Mean:

Impact: Outliers can skew the mean significantly, pulling it towards the extreme value. This is because the mean takes into account all values in the dataset.
Example: Consider the dataset: [10, 12, 14, 15, 16, 100].
The mean is 34.5
(10+12+14+15+16+100)/6=34.5.

The outlier (100) has greatly increased the mean, making it unrepresentative of the majority of the data.

Median:

Impact: The median, which is the middle value when the data is ordered, is less affected by outliers. It remains a more robust measure of central tendency in the presence of outliers.
Example: Using the same dataset [10, 12, 14, 15, 16, 100]:
When ordered: [10, 12, 14, 15, 16, 100], the median is the average of the 3rd and 4th values: 14.5

(14+15)/2=14.5

The median is not significantly impacted by the outlier (100) and remains a better representation of the dataset's central tendency.

Mode:

Impact: The mode (the most frequently occurring value) may be unaffected by outliers, especially if the outlier does not occur frequently.
Example: In the dataset [10, 12, 14, 15, 15, 100], the mode is 15, which remains unaffected by the outlier.

Effects on Measures of Dispersion:
Range:

Impact: Outliers can greatly increase the range, as the range is calculated as the difference between the maximum and minimum values.
Example: For the dataset [10, 12, 14, 15, 16, 100], the range is 90

100−10=90. The presence of the outlier (100) significantly increases the range
compared to a dataset without the outlier.

Variance and Standard Deviation:

Impact: Outliers can inflate both variance and standard deviation, as they increase the average squared deviation from the mean. This makes these measures less representative of the data's variability.

Example: Using the dataset [10, 12, 14, 15, 16, 100]:

Without the outlier, the variance is relatively low, indicating less spread. With the outlier included, the variance and standard deviation will be much higher, reflecting the increased spread caused by the extreme value.

Hence,
Mean: Highly sensitive to outliers; can be misleading.
Median: More robust measure; less affected by outliers.
Mode: Generally unaffected by outliers, depending on frequency.
Range: Can be greatly inflated by outliers.
Variance/Standard Deviation: Increased due to outliers, making them less representative of the dataset's variability.
Conclusion:
Outliers can skew the interpretation of a dataset, making it crucial to identify and consider their impact when analyzing data. In cases with significant outliers, using median and interquartile range (IQR) for central tendency and dispersion, respectively, may provide a clearer picture of the data's characteristics.

Thank You!